const data = {
    products: [
        {
            _id: "1",
            name: "Nike Slim Shirt",
            category: "Shirts",
            image: "https://amazona.webacademy.pro/images/p1.jpg",
            price: 120,
            countInStock: 10,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "Very high quality shirt",
        },
        {
            _id: "2",
            name: "Slim Pants",
            category: "Pants",
            image: "https://amazona.webacademy.pro/images/p2.jpg",
            price: 150,
            countInStock: 9,
            brand: "Adidas",
            rating: 3,
            numReviews: 8,
            description: "Very high quality pants",
        },
        {
            _id: "3",
            name: "Nike Slim Shirt",
            category: "Shirts",
            image: "https://amazona.webacademy.pro/images/p3.jpg",
            price: 120,
            countInStock: 25,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "Very high quality shirt",
        },
        {
            _id: "4",
            name: "Nike Slim Shirt",
            category: "Shirts",
            image: "https://amazona.webacademy.pro/images/p4.jpg",
            countInStock: 0,
            price: 120,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "Very high quality shirt",
        },
        {
            _id: "5",
            name: "Nike Slim Shirt",
            category: "Shirts",
            image: "https://amazona.webacademy.pro/images/p5.jpg",
            price: 120,
            countInStock: 44,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "Very high quality shirt",
        },
        {
            _id: "6",
            name: "Nike Slim Shirt",
            category: "Shirts",
            image: "https://amazona.webacademy.pro/images/p6.jpg",
            price: 120,
            countInStock: 10,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "Very high quality shirt",
        },
    ],
};

export default data;
